spring.application.name=architect-app
server.port=8082

# DB settings
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5402/auth_db}
spring.datasource.username=${DATABASE_USER:auth_user}
spring.datasource.password=${DATABASE_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

#settings of flyway
spring.flyway.enabled=true
spring.flyway.user=auth_user
spring.flyway.password=auth_pass
spring.flyway.url=jdbc:postgresql://localhost:5402/auth_db
