spring.application.name=auth-app
server.port=8081

# DB settings
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5403/tavern_keeper_db}
spring.datasource.username=${DATABASE_USER:auth_user}
spring.datasource.password=${DATABASE_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
